To from farm page tests
DEFRA/apha-apps-perms-move-animal-uat pull request #5
Opened 2024-11-11 17:44 UTC by eoin-corr-git

2024-11-12 11:54 UTC, hughfdjackson requested changes
Only change requested is for extra test & page title contents.

For the rest, they're more serving suggestions I'm happy to discuss (but don't need to block merging)

2024-11-12 11:54 UTC, hughfdjackson commented on test/specs/toFromFarm.spec.js
> +}
@eoin-corr-git  - you were talking earlier about isolating tests - maybe this is one of those junctures?

I'm guessing the alternative here is to put this test in landing.spec.js (e.g. have that test be responsible for verifying it goes to the current next step), and then start each of these tests already deep linked to the first question page?

2024-11-12 11:54 UTC, hughfdjackson commented on test/specs/toFromFarm.spec.js
> +        'Apply for an animal disease movement licence | Applications and permissions',
document title in the prototype is "Are you moving the cattle on or off your farm?"

2024-11-12 11:54 UTC, hughfdjackson commented on test/specs/toFromFarm.spec.js
> +      { timeout: 10000, timeoutMsg: 'Failed to load the landing page' }
timeout message is specific to landing page.  Is this one of those cases a generic helper would aid?

```
const wait = async (fn, message) =>
  await browser.waitUntil(fn, 
  { 
    timeout: 10000, timeoutMsg: 'Failed to load ${message}' 
  })
```

2024-11-12 11:54 UTC, hughfdjackson commented on test/specs/toFromFarm.spec.js
> +  })
We should add a test for javascript disabled, based on the discussion we just had?

2024-11-12 11:54 UTC, hughfdjackson commented on test/page-objects/toFromFarmPage.js
> +    await super.selectElement(this.offThefarmRadio, true)
Are these 'selectElement', 'selectContinue' and similar utilities would be be good candidates to make simple helper functions?

2024-11-12 12:37 UTC, eoin-corr-git commented on test/specs/toFromFarm.spec.js
> +}
Yep very good shout

2024-11-12 12:51 UTC, eoin-corr-git commented on test/specs/toFromFarm.spec.js
> +        'Apply for an animal disease movement licence | Applications and permissions',
Needs updating in UI too

2024-11-13 11:04 UTC, DrogoNevets requested changes

2024-11-13 11:06 UTC, hughfdjackson commented on test/specs/toFromFarm.spec.js
> +  beforeEach('Navigate to landing page', async () => {
Navigate to 'to or from farm' page?

2024-11-13 11:17 UTC, DrogoNevets requested changes

2024-11-13 11:17 UTC, DrogoNevets commented on package.json
> +    "test-nojs": "wdio run wdioNJS.conf.js",
following the naming convention from the ui repo I suggest
`test:js`
`test:nojs`

2024-11-13 11:18 UTC, DrogoNevets commented on package.json
> +    "test-nojs": "wdio run wdioNJS.conf.js",
and add in `test` which runs both

2024-11-13 11:19 UTC, hughfdjackson requested changes

2024-11-13 11:19 UTC, hughfdjackson commented on test/specs/toFromFarm.spec.js
> +    await expect(toFromFarmPage.offThefarmRadio).toBeSelected()
I think this will break once we add another page.  Maybe it's worth replacing `browser.refresh()` with going back in the history?

2024-11-13 11:34 UTC, eoin-corr-git commented on test/specs/toFromFarm.spec.js
> +    await expect(toFromFarmPage.offThefarmRadio).toBeSelected()
if you start on that page you can''t go back as there is no history
I'll update that test when we add the second question
I could add a test in the landing spec but it's overly convoluted and will need to change anyway

2024-11-13 11:38 UTC, DrogoNevets commented on test/specs/toFromFarm.spec.js
> +    await expect(toFromFarmPage.offThefarmRadio).toBeSelected()
if this is a journey test, it should start on the servcie start page no?

2024-11-13 11:41 UTC, eoin-corr-git commented on test/specs/toFromFarm.spec.js
> +    await expect(toFromFarmPage.offThefarmRadio).toBeSelected()
So planning to test the steps in as much isolation as possible. Hence there's a test on the landing spec that checks the navigation between those pages. Happy to review once we have more pages

2024-11-13 11:43 UTC, eoin-corr-git commented on test/specs/toFromFarm.spec.js
> +    await expect(toFromFarmPage.offThefarmRadio).toBeSelected()
Also we can add a larger journey test in there as well. I just also think it's good to keep as few dependants as possible for the majority

2024-11-13 11:45 UTC, hughfdjackson commented on .github/workflows/run-tests.yaml
> +      - name: Run the javascript enabled tests
npm test runs both js & nojs tests - update description?

2024-11-13 11:46 UTC, eoin-corr-git commented on .github/workflows/run-tests.yaml
> +      - name: Run the javascript enabled tests
Done

2024-11-13 11:47 UTC, hughfdjackson commented on test/specs/toFromFarm.spec.js
> +    await expect(toFromFarmPage.offThefarmRadio).toBeSelected()
When you press continue, you add the previous page to your history stack.  So when you do `selectOnFarmAndContinue()` and then `browser.back()`, you end up on the question page & can inspect the contents.

That works on my machine at least!

2024-11-13 12:33 UTC, merged